define([], function() {
  return {
    "AddColor": "Add Color",
    "ChartBar": "Bar",
    "ChartBarHorizontal": "Bar (Horizontal)",
    "ChartData": "Chart Data",
    "ChartDonut": "Donut",
    "ChartLine": "Line",
    "ChartPie": "Pie",
    "ChartSettings": "Chart Settings",
    "ChartStyle": "Chart Style",
    "ChartTitle": "Chart Title",
    "ChartType": "Chart Type",
    "Colors": "Colors",
    "DeleteColor": "Delete",
    "Error": "Something went wrong!",
    "Intro": "Select a list to continue...",
    "List": "List",
    "Loading": "Loading...",
    "LoadingChartData": "Loading chart data...",
    "PropertyPaneDescription": "Dash Settings",
    "Refresh": "Refresh",
    "SelectedFields": "Selected Fields",
  }
});
